4.Sistema/giga/comercio/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.FloatConverter, 'float')

urlpatterns = [
    path('clientes/listar/', views.ListarClientes.as_view(), name='listar_clientes'),
    path('clientes/adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('clientes/<int:pk>/editar/', views.editar_cliente, name='editar_cliente'),
    path('clientes/<int:pk>/deletar/', views.DeletarCliente.as_view(), name='deletar_cliente'),
    path('clientes/<int:pk>/editar-senha/', views.change_cliente_password, name='change_cliente_password'),
    path('colaboradores/listar/', views.ListarColaboradores.as_view(), name='listar_colaboradores'),
    path('colaboradores/adicionar/', views.adicionar_colaborador, name='adicionar_colaborador'),
    path('colaboradores/<int:pk>/editar/', views.editar_colaborador, name='editar_colaborador'),
    path('colaboradores/<int:pk>/deletar/', views.DeletarColaborador.as_view(), name='deletar_colaborador'),
    path('colaboradores/<int:pk>/editar-senha/', views.change_colaborador_password, name='change_colaborador_password'),
    path('produtos/listar/', views.ListarProdutos.as_view(), name='listar_produtos'),
    path('produtos/adicionar/', views.AdicionarProduto.as_view(), name='adicionar_produto'),
    path('produtos/<int:pk>/editar/', views.EditarProduto.as_view(), name='editar_produto'),
    path('produtos/<int:pk>/deletar/', views.DeletarProduto.as_view(), name='deletar_produto'),
    path('vendas/listar/', views.ListarVendas.as_view(), name='listar_vendas'),
    path('vendas/adicionar/', views.AdicionarVenda.as_view(), name='adicionar_venda'),
    path('vendas/finalizar/<int:pk>/<float:valor>/', views.finalizar_venda, name='finalizar_venda'),
    path('vendas/<int:pk>/editar/', views.EditarVenda.as_view(), name='editar_venda'),
    path('vendas/<int:pk>/deletar/', views.DeletarVenda.as_view(), name='deletar_venda'),
    path('vendas/adicionar/<int:pk>/itens/', views.AdicionarItem.as_view(), name='adicionar_item'),
    path('vendas/<int:pk>/deletar/item/<int:item_pk>/', views.DeletarItem.as_view(), name='deletar_item'),
    path('vendas/balanco/', views.VerBalanco.as_view(), name='ver_balanco'),
]

4.Sistema/giga/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/self-change-password/', views.self_change_password, name='self_change_password'),
]

4.Sistema/giga/giga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import handler404, handler403, handler500


handler404 = handler404
handler403 = handler403
handler500 = handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('comercio/', include(('comercio.urls', 'comercio'), namespace='comercio')),
]

4.Sistema/giga/comercio/models.py
from django.core.exceptions import PermissionDenied
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User, Permission
from django.db.models.signals import pre_save, post_save, post_delete, pre_delete, m2m_changed
from django.dispatch import receiver
from datetime import datetime


class Cliente(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cliente_user", null=True, blank=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    complemento = models.CharField(max_length=100)
    rua = models.CharField(max_length=100)
    numero = models.IntegerField()
    telefone = models.CharField(
        validators=[RegexValidator(regex='\([\d]{2}\) [\d]{5}-[\d]{4}', message='Telefone Inválido',
                                   code='nomatch')], max_length=15, null=True, blank=True)
    cpf = models.CharField(validators=[RegexValidator(regex='^\d{3}\.\d{3}\.\d{3}\-\d{2}$', message='CPF Inválido',
                                                      code='nomatch')], max_length=14)

    class Meta:
        ordering = ['user']
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class Colaborador(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="colaborador_user", null=True, blank=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    complemento = models.CharField(max_length=100)
    rua = models.CharField(max_length=100)
    numero = models.IntegerField()
    telefone = models.CharField(
        validators=[RegexValidator(regex='\([\d]{2}\) [\d]{5}-[\d]{4}', message='Telefone Inválido',
                                   code='nomatch')], max_length=15, null=True, blank=True)
    cpf = models.CharField(validators=[RegexValidator(regex='^\d{3}\.\d{3}\.\d{3}\-\d{2}$', message='CPF Inválido',
                                                      code='nomatch')], max_length=14)
    salario = models.FloatField()
    funcao = models.ForeignKey('FuncaoColaborador', on_delete=models.SET_NULL, null=True,
                               related_name='funcao_colaborador')

    class Meta:
        ordering = ['user']
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class FuncaoColaborador(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    permissoes = models.ManyToManyField(Permission, blank=True, verbose_name="Permissões",
                                        related_name='permissoes_funcao_colaborador')

    class Meta:
        ordering = ['nome']
        verbose_name = 'Função'
        verbose_name_plural = 'Funções'

    def __str__(self):
        return '{}'.format(self.nome)


class Produto(models.Model):
    nome = models.CharField(max_length=150)
    preco = models.FloatField()
    quantidade = models.PositiveIntegerField()

    class Meta:
        ordering = ['nome']
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return '{}'.format(self.nome)


class Venda(models.Model):
    valor = models.FloatField(blank=True, null=True)
    colaborador = models.ForeignKey(Colaborador, on_delete=models.CASCADE, related_name="venda_colaborador", null=True,
                                    blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name="venda_cliente", null=True,
                                blank=True)
    data_hora = models.DateTimeField(default=datetime.now, blank=True)

    METODO_PAGAMENTO_CHOICES = [
        (1, 'Cartão de Crédito'),
        (2, 'Cartão de Débito'),
        (3, 'Dinheiro'),
        (4, 'Pix'),
    ]

    metodo_pagamento = models.IntegerField(choices=METODO_PAGAMENTO_CHOICES)

    class Meta:
        ordering = ['valor']
        verbose_name = 'Venda'
        verbose_name_plural = 'Vendas'

    def __str__(self):
        return '{} - {}'.format(self.valor, self.cliente)


class Item(models.Model):
    quantidade = models.PositiveIntegerField(blank=True, null=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, related_name="itens_produto", null=True,
                                blank=True)
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE, related_name="itens_venda", null=True,
                              blank=True)
    descontado_estoque = models.BooleanField(blank=True, null=True)

    class Meta:
        ordering = ['produto']
        verbose_name = 'Item'
        verbose_name_plural = 'Itens'

    def __str__(self):
        return '{}'.format(self.produto)


@receiver(post_delete, sender=Cliente)
def delete_cliente(sender, instance, *args, **kwargs):
    if instance.user:
        User.objects.get(pk=instance.user.pk).delete()


@receiver(post_delete, sender=Colaborador)
def delete_colaborador(sender, instance, *args, **kwargs):
    if instance.user:
        User.objects.get(pk=instance.user.pk).delete()


@receiver(pre_delete, sender=User)
def delete_user(sender, instance, *args, **kwargs):
    if instance.cliente_user.all().first() is not None:
        raise PermissionDenied()
    elif instance.colaborador_user.all().first() is not None:
        raise PermissionDenied()


@receiver(post_save, sender=Colaborador)
def save_colaborador(sender, instance, created, *args, **kwargs):
    if created:
        if instance:
            user = instance.user
            for permission in instance.funcao.permissoes.all():
                user.user_permissions.add(permission)


@receiver(pre_save, sender=Colaborador)
def edit_colaborador(sender, instance, *args, **kwargs):
    if instance.id:
        colaborador = Colaborador.objects.get(id=instance.id)
        if colaborador.funcao != instance.funcao:
            user = instance.user
            user.user_permissions.set([])
            for permission in instance.funcao.permissoes.all():
                user.user_permissions.add(permission)


@receiver(m2m_changed, sender=FuncaoColaborador.permissoes.through)
def edit_colaborador(sender, instance, action, *args, **kwargs):
    if action in ["post_add", "post_remove", "post_clear"]:
        colaboradores = Colaborador.objects.filter(funcao=instance)
        for colaborador in colaboradores:
            user = colaborador.user
            user.user_permissions.set([])
            for permission in instance.permissoes.all():
                user.user_permissions.add(permission)

4.Sistema/giga/comercio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm
from .models import *


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = '__all__'
        labels = {'cpf': "CPF", 'numero': 'Número'}


class ColaboradorForm(forms.ModelForm):

    class Meta:
        model = Colaborador
        fields = '__all__'
        labels = {'cpf': "CPF", 'numero': 'Número', 'salario': 'Salário', 'funcao': 'Função'}


class VendaForm(forms.ModelForm):

    class Meta:
        model = Venda
        fields = '__all__'
        labels = {'metodo_pagamento': "Método de Pagamento", 'data_hora': "Data e Hora"}


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = '__all__'


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'
        labels = {'preco': "Preço"}


class UserForm(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'first_name',
            'last_name',
            'password1',
            'password2',
            'username',
            'email',
        ]


class EditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'email',
        ]


class EditClientePasswordForm(AdminPasswordChangeForm):

    class Meta:
        model = User
        fields = ['password1', 'password2', 'password']


class EditColaboradorPasswordForm(AdminPasswordChangeForm):

    class Meta:
        model = User
        fields = ['password1', 'password2', 'password']

4.Sistema/giga/comercio/templates/comercio/vendas/adicionar-venda.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 mt-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group {% if object.pk %}col-md-6{% else %}col-md-3{%endif %}">
                                {{ form.colaborador.label_tag }}
                                {% if form.colaborador.errors %}
                                {% render_field form.colaborador id='select-colaborador' class="form-control selectpicker is-invalid" title="Selecione um Colaborador"  name="colaborador" data-live-search="true" %}
                                <span class="text-danger"><small>{{ form.colaborador.errors }}</small></span>
                                {% else %}
                                {% render_field form.colaborador id='select-colaborador' class="form-control selectpicker" title="Selecione um Colaborador"  name="colaborador" data-live-search="true" %}
                                {% endif %}
                            </div>
                            <div class="form-group {% if object.pk %}col-md-6{% else %}col-md-3{% endif %}">
                                {{ form.cliente.label_tag }}
                                {% if form.cliente.errors %}
                                {% render_field form.cliente id='select-cliente' class="form-control selectpicker is-invalid" title="Selecione um Cliente"  name="cliente" data-live-search="true" %}
                                <span class="text-danger"><small>{{ form.cliente.errors }}</small></span>
                                {% else %}
                                {% render_field form.cliente id='select-cliente' class="form-control selectpicker" title="Selecione um Cliente"  name="cliente" data-live-search="true" %}
                                {% endif %}
                            </div>
                            <div class="form-group {% if object.pk %}col-md-4{% else %}col-md-3{% endif %}">
                                {{ form.data_hora.label_tag }}
                                {% if form.data_hora.errors %}
                                {% render_field form.data_hora class="form-control is-invalid" readonly='readonly' %}
                                <span class="text-danger"><small>{{ form.data_hora.errors }}</small></span>
                                {% else %}
                                {% render_field form.data_hora class="form-control" readonly='readonly' %}
                                {% endif %}
                            </div>
                            <div class="form-group {% if object.pk %}col-md-4{% else %}col-md-3{% endif %}">
                                {{ form.metodo_pagamento.label_tag }}
                                {% if form.metodo_pagamento.errors %}
                                {% render_field form.metodo_pagamento id='select-metodo-pagamento' class="form-control selectpicker is-invalid" title="Selecione um Método de Pagamento"  name="metodo_pagamento" data-live-search="true" %}
                                <span class="text-danger"><small>{{ form.metodo_pagamento.errors }}</small></span>
                                {% else %}
                                {% render_field form.metodo_pagamento id='select-metodo_pagamento' class="form-control selectpicker" title="Selecione um Método de Pagamento"  name="metodo_pagamento" data-live-search="true" %}
                                {% endif %}
                            </div>
                            {% if object.pk %}
                            <div class="form-group {% if object.pk %}col-md-4{% else %}col-md-3{% endif %}">
                                {{ form.valor.label_tag }}
                                {% if form.valor.errors %}
                                {% render_field form.valor class="form-control is-invalid" readonly='readonly' %}
                                <span class="text-danger"><small>{{ form.valor.errors }}</small></span>
                                {% else %}
                                {% render_field form.valor class="form-control" readonly='readonly' %}
                                {% endif %}
                            </div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary float-right">Prosseguir</button>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

{% block extrajs %}
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
{% endblock %}

4.Sistema/giga/comercio/templates/comercio/vendas/listar-vendas.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load extra_template_tags %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="modal fade" id="removeVendaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Deseja remover essa Venda?</h5>
            </div>
            <div class="modal-body" id="modal-delete-venda"></div>
            <div class="modal-footer">
                <form method="post" id="form-modal">
                    {% csrf_token %}
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-danger" type="submit">Remover</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 mt-4 mb-5">
            {% check_permission request.user "can_add_venda" as has_permission %}
            {% if has_permission or request.user.is_superuser %}
            <a type="button" href="{% url 'comercio:adicionar_venda' %}" class="btn btn-success mb-4">
                <i class="fas fa-plus"></i> Adicionar Venda
            </a>
            {% endif %}
            <div class="card mb-3">
                <div class="card-body">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                {{ filter.form.colaborador.label_tag }}
                                {% if filter.form.colaborador.errors %}
                                {% render_field filter.form.colaborador id='select-colaborador' class="form-control selectpicker is-invalid" title="Selecione um Colaborador"  name="colaborador" data-live-search="true" %}
                                <span class="text-danger"><small>{{ filter.form.colaborador.errors }}</small></span>
                                {% else %}
                                {% render_field filter.form.colaborador id='select-colaborador' class="form-control selectpicker" title="Selecione um Colaborador"  name="colaborador" data-live-search="true" %}
                                {% endif %}
                            </div>
                            <div class="form-group col-md-3">
                                {{ filter.form.cliente.label_tag }}
                                {% if filter.form.cliente.errors %}
                                {% render_field filter.form.cliente id='select-cliente' class="form-control selectpicker is-invalid" title="Selecione um Cliente"  name="cliente" data-live-search="true" %}
                                <span class="text-danger"><small>{{ filter.form.cliente.errors }}</small></span>
                                {% else %}
                                {% render_field filter.form.cliente id='select-cliente' class="form-control selectpicker" title="Selecione um Cliente"  name="cliente" data-live-search="true" %}
                                {% endif %}
                            </div>
                            <div class="form-group col-md-3">
                                {{ filter.form.metodo_pagamento.label_tag }}
                                {% if filter.form.metodo_pagamento.errors %}
                                {% render_field filter.form.metodo_pagamento id='select-metodo_pagamento' class="form-control selectpicker is-invalid" title="Selecione um Met. Pagamento"  name="metodo_pagamento" data-live-search="true" %}
                                <span class="text-danger"><small>{{ filter.form.metodo_pagamento.errors }}</small></span>
                                {% else %}
                                {% render_field filter.form.metodo_pagamento id='select-metodo_pagamento' class="form-control selectpicker" title="Selecione um Met. Pagamento"  name="metodo_pagamento" data-live-search="true" %}
                                {% endif %}
                            </div>
                            <div class="form-group col-md-3">
                                <label for="id_data_hora">Data:</label>
                                {% if filter.form.data_hora.errors %}
                                {% render_field filter.form.data_hora class="form-control is-invalid"%}
                                <span class="text-danger"><small>{{ filter.form.data_hora.errors }}</small></span>
                                {% else %}
                                {% render_field filter.form.data_hora class="form-control" %}
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary float-right" id="form-add-project-submit">Filtrar</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <table id="table" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Colaborador</th>
                                <th>Valor</th>
                                <th>Cliente</th>
                                <th>Data e Hora</th>
                                <th>Met. Pagamento</th>
                                {% check_permission request.user "can_edit_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Editar</th>
                                {% endif %}
                                {% check_permission request.user "can_delete_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Excluir</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for venda in object_list %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td>{{ venda.colaborador }}</td>
                                <td>R$ {{ venda.valor|floatformat:2 }}</td>
                                <td>{{ venda.cliente }}</td>
                                <td>{{ venda.data_hora }}</td>
                                <td>{{ venda.get_metodo_pagamento_display }}</td>
                                {% check_permission request.user "can_edit_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <td class="text-center">
                                    <a type="button" class="btn btn-primary rounded-circle" href="{% url 'comercio:editar_venda' pk=venda.pk %}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                </td>
                                {% endif %}
                                {% check_permission request.user "can_delete_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <td class="text-center">
                                    <a href="#" name="{{ venda.valor }}" id="{{ venda.pk }}" class="btn btn-danger rounded-circle" onclick="modalDeleteVenda(this)" data-toggle="modal" data-target="#removeVendaModal">
                                        <i class="fas fa-ban"></i>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Colaborador</th>
                                <th>Valor</th>
                                <th>Cliente</th>
                                <th>Data e Hora</th>
                                <th>Met. Pagamento</th>
                                {% check_permission request.user "can_edit_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Editar</th>
                                {% endif %}
                                {% check_permission request.user "can_delete_venda" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Excluir</th>
                                {% endif %}
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.11.3/filtering/type-based/accent-neutralise.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable( {
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.25/i18n/Portuguese-Brasil.json'
            },
            responsive: true
        } );
    } );
</script>

<script>
    function modalDeleteVenda(triggeringLink) {
        var nome = triggeringLink.name;
        var id = triggeringLink.id;
        var url = "{% url 'comercio:deletar_venda' pk=12345 %}".replace(/12345/, id.toString());
        $('#form-modal').attr('action', url);
        $("#modal-delete-venda").html('Selecione "Remover" abaixo para remover a venda de Valor: '+' <b>' + 'R$ ' + nome + '</b>')
    }
</script>

<script>
    $(document).ready(function(){
        $('#id_data_hora').mask('00/00/0000');
    });
</script>

{% endblock %}