4.Sistema/giga/comercio/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.FloatConverter, 'float')

urlpatterns = [
    path('clientes/listar/', views.ListarClientes.as_view(), name='listar_clientes'),
    path('clientes/adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('clientes/<int:pk>/editar/', views.editar_cliente, name='editar_cliente'),
    path('clientes/<int:pk>/deletar/', views.DeletarCliente.as_view(), name='deletar_cliente'),
    path('clientes/<int:pk>/editar-senha/', views.change_cliente_password, name='change_cliente_password'),
    path('colaboradores/listar/', views.ListarColaboradores.as_view(), name='listar_colaboradores'),
    path('colaboradores/adicionar/', views.adicionar_colaborador, name='adicionar_colaborador'),
    path('colaboradores/<int:pk>/editar/', views.editar_colaborador, name='editar_colaborador'),
    path('colaboradores/<int:pk>/deletar/', views.DeletarColaborador.as_view(), name='deletar_colaborador'),
    path('colaboradores/<int:pk>/editar-senha/', views.change_colaborador_password, name='change_colaborador_password'),
    path('produtos/listar/', views.ListarProdutos.as_view(), name='listar_produtos'),
    path('produtos/adicionar/', views.AdicionarProduto.as_view(), name='adicionar_produto'),
    path('produtos/<int:pk>/editar/', views.EditarProduto.as_view(), name='editar_produto'),
    path('produtos/<int:pk>/deletar/', views.DeletarProduto.as_view(), name='deletar_produto'),
    path('vendas/listar/', views.ListarVendas.as_view(), name='listar_vendas'),
    path('vendas/adicionar/', views.AdicionarVenda.as_view(), name='adicionar_venda'),
    path('vendas/finalizar/<int:pk>/<float:valor>/', views.finalizar_venda, name='finalizar_venda'),
    path('vendas/<int:pk>/editar/', views.EditarVenda.as_view(), name='editar_venda'),
    path('vendas/<int:pk>/deletar/', views.DeletarVenda.as_view(), name='deletar_venda'),
    path('vendas/adicionar/<int:pk>/itens/', views.AdicionarItem.as_view(), name='adicionar_item'),
    path('vendas/<int:pk>/deletar/item/<int:item_pk>/', views.DeletarItem.as_view(), name='deletar_item'),
    path('vendas/balanco/', views.VerBalanco.as_view(), name='ver_balanco'),
]

4.Sistema/giga/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/self-change-password/', views.self_change_password, name='self_change_password'),
]

4.Sistema/giga/giga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import handler404, handler403, handler500


handler404 = handler404
handler403 = handler403
handler500 = handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('comercio/', include(('comercio.urls', 'comercio'), namespace='comercio')),
]

4.Sistema/giga/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect


@login_required
def index(request):
    return render(request, 'core/index.html')


# Tela de alteração de Senha do Usuário por parte do próprio Usuário
@login_required
def self_change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('core:index')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'core/user/self-change-password.html', {'form': form})

4.Sistema/giga/core/templates/core/base.html
{% load static %}
{% load extra_template_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Giga Vendas</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    {% block extracss %}
    {% endblock %}
    {% block chartsjs %}
    {% endblock %}

    </head>
    <body class="sb-nav-fixed" id="sidenavMenu">
        <!-- Logout Modal-->
         <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
               <div class="modal-content">
                  <div class="modal-header">
                     <h5 class="modal-title" id="exampleModalLabel">Deseja Sair?</h5>
                  </div>
                  <div class="modal-body">Selecione "Logout" abaixo para encerrar sua sessão atual.</div>
                  <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                     <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
                  </div>
               </div>
            </div>
         </div>
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" style="height: 65px">
            <!-- Navbar Brand-->
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <a class="navbar-brand ml-3" href="{% url 'core:index' %}">
                GigaVendas
            </a>
            <!-- Navbar-->

            <ul class="navbar-nav -md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if request.user.first_name %}{{ request.user.first_name }} {{ request.user.last_name }}{% else %}{{ request.user.username }}{% endif %}
                         &nbsp<i class="fas fa-user fa-fw"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'core:self_change_password' %}">Alterar Senha</a></li>
                        <li><a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>

        <div id="layoutSidenav" class="mt-3">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            {% check_permission request.user "can_see_clientes" as has_permission_cliente %}
                            {% check_permission request.user "can_see_colaboradores" as has_permission_colaborador %}
                            {% if has_permission_cliente or has_permission_colaborador or request.user.is_superuser %}
                            <div class="sb-sidenav-menu-heading">Usuários</div>
                            {% endif %}
                            {% if has_permission_cliente or request.user.is_superuser %}
                            <a class="nav-link {% if request.resolver_match.url_name == 'listar_clientes' or request.resolver_match.url_name == 'adicionar_cliente' or request.resolver_match.url_name == 'editar_cliente' or request.resolver_match.url_name == 'change_cliente_password' %}active{% endif %}" href="{% url 'comercio:listar_clientes' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-user-friends"></i></div>
                                Clientes
                            </a>
                            {% endif %}
                            {% if has_permission_colaborador or request.user.is_superuser %}
                            <a class="nav-link {% if request.resolver_match.url_name == 'listar_colaboradores' or request.resolver_match.url_name == 'adicionar_colaborador' or request.resolver_match.url_name == 'editar_colaborador' or request.resolver_match.url_name == 'change_colaborador_password' %}active{% endif %}" href="{% url 'comercio:listar_colaboradores' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-user-friends"></i></div>
                                Colaboradores
                            </a>
                            {% endif %}
                            {% check_permission request.user "can_see_produtos" as has_permission_projeto %}
                            {% if has_permission_projeto or request.user.is_superuser %}
                            <div class="sb-sidenav-menu-heading">Produtos</div>
                            <a class="nav-link {% if request.resolver_match.url_name == 'listar_produtos' or request.resolver_match.url_name == 'adicionar_produto' or request.resolver_match.url_name == 'editar_produto' %}active{% endif %}" href="{% url 'comercio:listar_produtos' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                                Ver Produtos
                            </a>
                            {% endif %}
                            {% check_permission request.user "can_see_vendas" as has_permission_venda %}
                            {% if has_permission_venda or request.user.is_superuser %}
                            <div class="sb-sidenav-menu-heading">Vendas</div>
                            <a class="nav-link {% if request.resolver_match.url_name == 'listar_vendas' or request.resolver_match.url_name == 'adicionar_venda' or request.resolver_match.url_name == 'editar_venda' or request.resolver_match.url_name == 'adicionar_item' %}active{% endif %}" href="{% url 'comercio:listar_vendas' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                                Ver Vendas
                            </a>
                            {% endif %}
                            {% check_permission request.user "can_see_balanco" as has_permission_balanco %}
                            {% if has_permission_balanco or request.user.is_superuser %}
                            <div class="sb-sidenav-menu-heading">Financeiro</div>
                            <a class="nav-link {% if request.resolver_match.url_name == 'ver_balanco' %}active{% endif %}" href="{% url 'comercio:ver_balanco' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-coins"></i></div>
                                Balanços
                            </a>
                            {% endif %}

                            <div class="mt-4 text-center">
                                <div id="google_translate_element"></div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>

    <script>
        const sidebar_collapse = (localStorage.getItem('sb|sidebar-toggle'));
        const sidebar = $('#sidenavMenu');

        if (sidebar_collapse === "true") {
            sidebar.addClass('sb-sidenav-toggled');
        } else{
            sidebar.removeClass('sb-sidenav-toggled');
        }
    </script>
    <script type="text/javascript">
        function googleTranslateElementInit() {
          new google.translate.TranslateElement({pageLanguage: 'pt-br', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
        }
    </script>
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    {% block extrajs %}
    {% endblock %}
    </body>
</html>

4.Sistema/giga/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block extracss %}
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
{% endblock %}
{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 my-4">
            <div class="card">
                <div class="card-body">
                    <img class="w-100 h-100"  src="{% static 'img/coachability-3.png' %}">
                </div>
            </div>
        </div>
    </main>
</div>
{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{% static 'js/datatables-simple.js' %}"></script>

{% endblock %}
{% endblock %}

4.Sistema/giga/core/templates/core/login.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

        <title>Reporter Intelliway</title>
        <!-- Font Awesome -->

        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
            rel="stylesheet"
            />
        <!-- Google Fonts -->
        <link
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"
            />
        <!-- MDB -->
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
            rel="stylesheet"
            />
        <style>
            .divider:after,
              .divider:before {
                content: "";
                flex: 1;
                height: 1px;
                background: #eee;
              }
              .h-custom {
                height: calc(100% - 73px);
              }
              @media (max-width: 450px) {
                .h-custom {
                height: 100%;
                }
            }
        </style>
    </head>
    <body>
        <section class="vh-100">
            <div class="container-fluid h-custom">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-md-9 col-lg-6 col-xl-5">
                        <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-login-form/draw2.png" class="img-fluid"
                            alt="Sample image">
                    </div>
                    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                        <form method="post">
                          {% if form.errors %}
                          <span class="text-danger"><small>{{ form.non_field_errors }}</small></span>
                          {% endif %}
                          {% csrf_token %}
                            <div class="form-outline mb-3">
                                {% render_field form.username class="form-control form-control-lg" placeholder="Usuário" %}
                            </div>
                            <!-- Password input -->
                            <div class="form-outline mb-3">
                                {% render_field form.password class="form-control form-control-lg" placeholder="Senha" %}
                            </div>
                            <div class="text-center text-lg-start mt-4 pt-2">
                                <button type="submit" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-dark">
                <!-- Copyright -->
                <div class="text-white mb-3 mb-md-0">
                    Copyright &copy; Intelliway <script>document.write(new Date().getFullYear())</script>. Todos os direitos reservados.
                </div>
            </div>
        </section>
        <!-- MDB -->
        <script
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
            ></script>
    </body>
</html>