4.Sistema/giga/comercio/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.FloatConverter, 'float')

urlpatterns = [
    path('clientes/listar/', views.ListarClientes.as_view(), name='listar_clientes'),
    path('clientes/adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('clientes/<int:pk>/editar/', views.editar_cliente, name='editar_cliente'),
    path('clientes/<int:pk>/deletar/', views.DeletarCliente.as_view(), name='deletar_cliente'),
    path('clientes/<int:pk>/editar-senha/', views.change_cliente_password, name='change_cliente_password'),
    path('colaboradores/listar/', views.ListarColaboradores.as_view(), name='listar_colaboradores'),
    path('colaboradores/adicionar/', views.adicionar_colaborador, name='adicionar_colaborador'),
    path('colaboradores/<int:pk>/editar/', views.editar_colaborador, name='editar_colaborador'),
    path('colaboradores/<int:pk>/deletar/', views.DeletarColaborador.as_view(), name='deletar_colaborador'),
    path('colaboradores/<int:pk>/editar-senha/', views.change_colaborador_password, name='change_colaborador_password'),
    path('produtos/listar/', views.ListarProdutos.as_view(), name='listar_produtos'),
    path('produtos/adicionar/', views.AdicionarProduto.as_view(), name='adicionar_produto'),
    path('produtos/<int:pk>/editar/', views.EditarProduto.as_view(), name='editar_produto'),
    path('produtos/<int:pk>/deletar/', views.DeletarProduto.as_view(), name='deletar_produto'),
    path('vendas/listar/', views.ListarVendas.as_view(), name='listar_vendas'),
    path('vendas/adicionar/', views.AdicionarVenda.as_view(), name='adicionar_venda'),
    path('vendas/finalizar/<int:pk>/<float:valor>/', views.finalizar_venda, name='finalizar_venda'),
    path('vendas/<int:pk>/editar/', views.EditarVenda.as_view(), name='editar_venda'),
    path('vendas/<int:pk>/deletar/', views.DeletarVenda.as_view(), name='deletar_venda'),
    path('vendas/adicionar/<int:pk>/itens/', views.AdicionarItem.as_view(), name='adicionar_item'),
    path('vendas/<int:pk>/deletar/item/<int:item_pk>/', views.DeletarItem.as_view(), name='deletar_item'),
    path('vendas/balanco/', views.VerBalanco.as_view(), name='ver_balanco'),
]

4.Sistema/giga/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/self-change-password/', views.self_change_password, name='self_change_password'),
]

4.Sistema/giga/giga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import handler404, handler403, handler500


handler404 = handler404
handler403 = handler403
handler500 = handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('comercio/', include(('comercio.urls', 'comercio'), namespace='comercio')),
]

4.Sistema/giga/comercio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm
from .models import *


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = '__all__'
        labels = {'cpf': "CPF", 'numero': 'Número'}


class ColaboradorForm(forms.ModelForm):

    class Meta:
        model = Colaborador
        fields = '__all__'
        labels = {'cpf': "CPF", 'numero': 'Número', 'salario': 'Salário', 'funcao': 'Função'}


class VendaForm(forms.ModelForm):

    class Meta:
        model = Venda
        fields = '__all__'
        labels = {'metodo_pagamento': "Método de Pagamento", 'data_hora': "Data e Hora"}


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = '__all__'


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'
        labels = {'preco': "Preço"}


class UserForm(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'first_name',
            'last_name',
            'password1',
            'password2',
            'username',
            'email',
        ]


class EditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'email',
        ]


class EditClientePasswordForm(AdminPasswordChangeForm):

    class Meta:
        model = User
        fields = ['password1', 'password2', 'password']


class EditColaboradorPasswordForm(AdminPasswordChangeForm):

    class Meta:
        model = User
        fields = ['password1', 'password2', 'password']

4.Sistema/giga/comercio/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from django.db.models import QuerySet
from django.http import Http404, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from .models import *
from .filters import *
from .forms import *
from django.contrib import messages


@login_required
def adicionar_cliente(request):
    if request.user.has_perm("global_permissions.can_add_cliente"):
        if request.method == 'POST':

            # Trata os dois formulários, tanto o de usuário comum, como o personalizado de ClientPermissions
            form = UserForm(data=request.POST)
            user_form = ClienteForm(data=request.POST)

            if form.is_valid() and user_form.is_valid():
                user = form.save(commit=False)
                user.is_active = True
                user.save()
                aux = user_form.save(commit=False)
                aux.user = user
                aux.save()
                return redirect('comercio:listar_clientes')
        else:
            form = UserForm()
            user_form = ClienteForm()
        return render(request, 'comercio/clientes/adicionar-cliente.html',
                      {'form': form, 'user_form': user_form})
    else:
        raise PermissionDenied()


# Tela para editar Usuário cadastrado
@login_required
def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    user = cliente.user
    if request.user.has_perm("global_permissions.can_edit_cliente"):
        if request.method == 'POST':
            form = EditUserForm(data=request.POST, instance=user)
            user_form = ClienteForm(data=request.POST, instance=cliente)
            if form.is_valid() and user_form.is_valid():
                user = form.save()
                aux = user_form.save(commit=False)
                aux.user = user
                aux.save()
                return redirect('comercio:listar_clientes')
        else:
            form = EditUserForm(instance=user)
            user_form = ClienteForm(instance=cliente)
        return render(request, 'comercio/clientes/editar-cliente.html',
                      {'form': form, 'user_form': user_form, 'usuario': user})
    else:
        raise PermissionDenied()


# Tela de alteração de Senha do Usuário por parte do Admin
@login_required
def change_cliente_password(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.cliente_user:
        if request.user.has_perm("can_edit_cliente_password"):
            if request.method == 'POST':
                form = EditClientePasswordForm(data=request.POST, user=user)
                if form.is_valid():
                    form.save()
                    return redirect('comercio:listar_clientes')
            else:
                form = EditClientePasswordForm(user=user)
            return render(request, 'comercio/clientes/change-cliente-password.html',
                          {'form': form, 'usuario': user})
        else:
            raise PermissionDenied()
    else:
        raise Http404


@method_decorator(login_required, name='dispatch')
class ListarClientes(PermissionRequiredMixin, ListView):
    model = Cliente
    permission_required = 'global_permissions.can_see_clientes'
    raise_exception = True
    template_name = 'comercio/clientes/listar-clientes.html'


@method_decorator(login_required, name='dispatch')
class DeletarCliente(PermissionRequiredMixin, DeleteView):
    model = Cliente
    permission_required = 'global_permissions.can_delete_cliente'
    raise_exception = True
    template_name = 'clientes/listar_clientes.html'
    success_url = reverse_lazy('comercio:listar_clientes')


@login_required
def adicionar_colaborador(request):
    if request.user.has_perm("global_permissions.can_add_colaborador"):
        if request.method == 'POST':
            form = UserForm(data=request.POST)
            user_form = ColaboradorForm(data=request.POST)

            if form.is_valid() and user_form.is_valid():
                user = form.save(commit=False)
                user.is_active = True
                user.save()
                aux = user_form.save(commit=False)
                aux.user = user
                aux.save()
                return redirect('comercio:listar_colaboradores')
        else:
            form = UserForm()
            user_form = ColaboradorForm()
        return render(request, 'comercio/colaboradores/adicionar-colaborador.html',
                      {'form': form, 'user_form': user_form})
    else:
        raise PermissionDenied()


# Tela para editar Usuário cadastrado
@login_required
def editar_colaborador(request, pk):
    colaborador = get_object_or_404(Colaborador, pk=pk)
    user = colaborador.user
    if request.user.has_perm("global_permissions.can_edit_colaborador"):
        if request.method == 'POST':
            form = EditUserForm(data=request.POST, instance=user)
            user_form = ColaboradorForm(data=request.POST, instance=colaborador)
            if form.is_valid() and user_form.is_valid():
                user = form.save()
                aux = user_form.save(commit=False)
                aux.user = user
                aux.save()
                return redirect('comercio:listar_colaboradores')
        else:
            form = EditUserForm(instance=user)
            user_form = ColaboradorForm(instance=colaborador)
        return render(request, 'comercio/colaboradores/editar-colaborador.html',
                      {'form': form, 'user_form': user_form, 'usuario': user})
    else:
        raise PermissionDenied()


# Tela de alteração de Senha do Usuário por parte do Admin
@login_required
def change_colaborador_password(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.colaborador_user:
        if request.user.has_perm("can_edit_colaborador_password"):
            if request.method == 'POST':
                form = EditColaboradorPasswordForm(data=request.POST, user=user)
                if form.is_valid():
                    form.save()
                    return redirect('comercio:listar_colaboradores')
            else:
                form = EditColaboradorPasswordForm(user=user)
            return render(request, 'comercio/colaboradores/change-colaborador-password.html',
                          {'form': form, 'usuario': user})
        else:
            raise PermissionDenied()
    else:
        raise Http404


@method_decorator(login_required, name='dispatch')
class ListarColaboradores(PermissionRequiredMixin, ListView):
    model = Colaborador
    permission_required = 'global_permissions.can_see_colaboradores'
    raise_exception = True
    template_name = 'comercio/colaboradores/listar-colaboradores.html'


@method_decorator(login_required, name='dispatch')
class DeletarColaborador(PermissionRequiredMixin, DeleteView):
    model = Colaborador
    permission_required = 'global_permissions.can_delete_colaborador'
    raise_exception = True
    template_name = 'colaboradores/listar-colaboradores.html'
    success_url = reverse_lazy('comercio:listar_colaboradores')


@method_decorator(login_required, name='dispatch')
class AdicionarProduto(PermissionRequiredMixin, CreateView):
    model = Produto
    form_class = ProdutoForm
    permission_required = 'global_permissions.can_add_produto'
    raise_exception = True
    template_name = 'comercio/produtos/adicionar-produto.html'
    success_url = reverse_lazy('comercio:listar_produtos')


@method_decorator(login_required, name='dispatch')
class ListarProdutos(PermissionRequiredMixin, ListView):
    model = Produto
    permission_required = 'global_permissions.can_see_produtos'
    raise_exception = True
    template_name = 'comercio/produtos/listar-produtos.html'


@method_decorator(login_required, name='dispatch')
class EditarProduto(PermissionRequiredMixin, UpdateView):
    model = Produto
    form_class = ProdutoForm
    permission_required = 'global_permissions.can_edit_produto'
    raise_exception = True
    template_name = 'comercio/produtos/adicionar-produto.html'
    success_url = reverse_lazy('comercio:listar_produtos')


@method_decorator(login_required, name='dispatch')
class DeletarProduto(PermissionRequiredMixin, DeleteView):
    model = Produto
    permission_required = 'global_permissions.can_delete_produto'
    raise_exception = True
    template_name = 'comercio/produtos/listar-produtos.html'
    success_url = reverse_lazy('comercio:listar_produtos')


@method_decorator(login_required, name='dispatch')
class AdicionarVenda(PermissionRequiredMixin, CreateView):
    model = Venda
    form_class = VendaForm
    permission_required = 'global_permissions.can_add_venda'
    raise_exception = True
    template_name = 'comercio/vendas/adicionar-venda.html'

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('comercio:adicionar_item', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


def finalizar_venda(request, pk, valor):
    try:
        venda = Venda.objects.get(pk=pk)
        venda.valor = valor
        venda.save()

        for item in venda.itens_venda.all():
            if not item.descontado_estoque:
                item.produto.quantidade -= item.quantidade
                item.produto.save()
                item.descontado_estoque = True
                item.save()
        return redirect('comercio:listar_vendas')
    except Venda.DoesNotExist:
        return Http404


@method_decorator(login_required, name='dispatch')
class ListarVendas(PermissionRequiredMixin, ListView):
    model = Venda

4.Sistema/giga/comercio/templates/comercio/produtos/adicionar-produto.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 mt-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                {{ form.nome.label_tag }}
                                {% if form.nome.errors %}
                                {% render_field form.nome class="form-control is-invalid"%}
                                <span class="text-danger"><small>{{ form.nome.errors }}</small></span>
                                {% else %}
                                {% render_field form.nome class="form-control" %}
                                {% endif %}
                            </div>
                            <div class="form-group col-md-3">
                                {{ form.preco.label_tag }}
                                {% if form.preco.errors %}
                                {% render_field form.preco class="form-control is-invalid"%}
                                <span class="text-danger"><small>{{ form.preco.errors }}</small></span>
                                {% else %}
                                {% render_field form.preco class="form-control" %}
                                {% endif %}
                            </div>
                            <div class="form-group col-md-3">
                                {{ form.quantidade.label_tag }}
                                {% if form.quantidade.errors %}
                                {% render_field form.quantidade class="form-control is-invalid"%}
                                <span class="text-danger"><small>{{ form.quantidade.errors }}</small></span>
                                {% else %}
                                {% render_field form.quantidade class="form-control" %}
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-2 float-right">{% if object.pk %}Editar{% else %}Adicionar{% endif %}</button>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

{% block extrajs %}
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
{% endblock %}

4.Sistema/giga/comercio/templates/comercio/produtos/listar-produtos.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load extra_template_tags %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="modal fade" id="removeProdutoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Deseja remover esse Produto?</h5>
            </div>
            <div class="modal-body" id="modal-delete-produto"></div>
            <div class="modal-footer">
                <form method="post" id="form-modal">
                    {% csrf_token %}
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-danger" type="submit">Remover</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 mt-4 mb-5">
            {% check_permission request.user "can_add_produto" as has_permission %}
            {% if has_permission or request.user.is_superuser %}
            <a type="button" href="{% url 'comercio:adicionar_produto' %}" class="btn btn-success mb-4">
                <i class="fas fa-plus"></i> Adicionar Produto
            </a>
            {% endif %}
            <div class="card">
                <div class="card-body">
                    <table id="table" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Preço</th>
                                <th>Quantidade</th>
                                {% check_permission request.user "can_edit_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Editar</th>
                                {% endif %}
                                {% check_permission request.user "can_delete_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Excluir</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for produto in object_list %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td>{{ produto.nome }}</td>
                                <td>{{ produto.preco }}</td>
                                <td>{{ produto.quantidade }}</td>
                                {% check_permission request.user "can_edit_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <td class="text-center">
                                    <a type="button" class="btn btn-primary rounded-circle" href="{% url 'comercio:editar_produto' pk=produto.pk %}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                </td>
                                {% endif %}
                                {% check_permission request.user "can_delete_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <td class="text-center">
                                    <a href="#" name="{{ produto.nome }}" id="{{ produto.pk }}" class="btn btn-danger rounded-circle" onclick="modalDeleteProduto(this)" data-toggle="modal" data-target="#removeProdutoModal">
                                        <i class="fas fa-ban"></i>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Preço</th>
                                <th>Quantidade</th>
                                {% check_permission request.user "can_edit_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Editar</th>
                                {% endif %}
                                {% check_permission request.user "can_delete_produto" as has_permission %}
                                {% if has_permission or request.user.is_superuser %}
                                <th>Excluir</th>
                                {% endif %}
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.11.3/filtering/type-based/accent-neutralise.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable( {
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.25/i18n/Portuguese-Brasil.json'
            },
            responsive: true
        } );
    } );
</script>

<script>
    function modalDeleteProduto(triggeringLink) {
        var nome = triggeringLink.name;
        var id = triggeringLink.id;
        var url = "{% url 'comercio:deletar_produto' pk=12345 %}".replace(/12345/, id.toString());
        $('#form-modal').attr('action', url);
        $("#modal-delete-produto").html('Selecione "Remover" abaixo para remover o produto: '+' <b>' + nome + '</b>')
    }
</script>

{% endblock %}